# Generated by Django 3.1 on 2020-08-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', help_text='Enter a locale as per <a href="https://stackoverflow.com/questions/3191664/list-of-all-locales-and-their-short-codes">this post</a>', max_length=100, verbose_name='Language'),
            preserve_default=False,
        ),
    ]
